# Generated by Django 4.1.6 on 2023-03-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('date_of_procurement', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('school', models.ForeignKey(default='school', on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school')),
            ],
        ),
    ]
