# Generated by Django 4.1.6 on 2023-03-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school'),
        ),
    ]
