# Generated by Django 4.1.6 on 2023-03-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_accesskey_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskey',
            name='school',
        ),
    ]
